import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  content: [
    "./components/**/*.{vue,js,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
  ],
  theme: {
    extend: {
      colors: {
        main: {
          DEFAULT: "var(--bg_color)",
          success: "var(--success_color)",
          success2: "var(--success_color2)",
          success3: "var(--success_color3)",
          success4: "var(--success_color4)",
          success5: "var(--success_color5)",
          success6: "var(--success_color6)",
          success7: "var(--success_color7)",
          success8: "var(--success_color8)",
          success9: "var(--success_color9)",
          1: "var(--bg_color)",
          2: "var(--bg_color2)",
          3: "var(--bg_color3)",
          4: "var(--bg_color4)",
          5: "var(--bg_color5)",
          6: "var(--bg_color6)",
          7: "var(--bg_color7)",
          8: "var(--bg_color8)",
          9: "var(--bg_color9)",
          10: "var(--bg_color10)",
          11: "var(--bg_color11)",
          12: "var(--bg_color12)",
          13: "var(--bg_color13)",
          14: "var(--bg_color14)",
          15: "var(--bg_color15)",
          16: "var(--bg_color16)",
          17: "var(--bg_color17)",
          18: "var(--bg_color18)",
          19: "var(--bg_color19)",
          20: "var(--bg_color20)",
          21: "var(--bg_color21)",
          22: "var(--bg_color22)",
          23: "var(--bg_color23)",
          24: "var(--bg_color24)",
          25: "var(--bg_color25)",
          26: "var(--bg_color26)",
        },
        font: {
          DEFAULT: "var(--text_light)",
          danger: "var(--danger_color)",
          danger2: "var(--danger_color2)",
          danger3: "var(--danger_color3)",
          danger4: "var(--danger_color4)",
          danger5: "var(--danger_color5)",
          danger6: "var(--danger_color6)",
          danger7: "var(--danger_color7)",
          danger8: "var(--danger_color8)",
          danger9: "var(--danger_color9)",
          1: "var(--text_dark)",
          2: "var(--text_dark2)",
          3: "var(--text_dark3)",
          4: "var(--text_dark4)",
          5: "var(--text_dark5)",
          6: "var(--text_dark6)",
          7: "var(--text_dark7)",
          8: "var(--text_dark8)",
          9: "var(--text_dark9)",
          10: "var(--text_dark10)",
          11: "var(--text_dark11)",
          12: "var(--text_dark12)",
          13: "var(--text_dark13)",
          14: "var(--text_dark14)",
          15: "var(--text_dark15)",
          16: "var(--text_dark16)",
          17: "var(--text_dark17)",
          18: "var(--text_dark18)",
          19: "var(--text_dark19)",
          20: "var(--text_dark20)",
          21: "var(--text_dark21)",
          22: "var(--text_dark22)",
          23: "var(--text_dark23)",
        },
        bc: {
          DEFAULT: "var(--border_color)",
          1: "var(--border_color)",
          2: "var(--border_color2)",
          3: "var(--border_color3)",
          4: "var(--border_color4)",
          5: "var(--border_color5)",
          6: "var(--border_color6)",
          7: "var(--border_color7)",
          8: "var(--border_color8)",
          9: "var(--border_color9)",
          10: "var(--border_color10)",
          11: "var(--border_color11) !important",
          12: "var(--border_color12)",
          13: "var(--border_color13)",
          14: "var(--border_color14)",
          15: "var(--border_color15)",
        },
      },
      fontSize: {
        xs: "var(--text_xs)",
        sm: "var(--text_sm)",
        md: "var(--text_md)",
        lg: "var(--text_lg)",
        xl: "var(--text_xl)",
        p: "var(--text_p)",
      },
      fontFamily: {
        Lora: "Lora, sans-serif !important",
        Inter: "Inter, sans-serif !important",
        rhd: "'Red Hat Display', sans-serif !important",
        cg: "'Cormorant Garamond', sans-serif !important",
      },
    },
  },
  plugins: [],
};
