export default {
  user: {
    id: "9b57c550-7752-4470-8e44-a2d9698674bb-3232",
    uuid: 0,
    first_name: "Beezlinq",
    last_name: "User",
    full_name: "Beezlinq User",
    username: "beez-user",
    email: "noreply@beezlinq.com",
    free_trial_status: "currently_on",
    total_scans_used: 0,
    total_scans_purchased: 0,
    scan_bonus_from_subscription: 0,
    total_scans_remaining: 0,
    cummulative_scans: 0,
    connection_count: 0,
    phone_number: "11111111",
    country: "Nigeria",
    state: "Federal Capital Territory",
    city: "Abuja",
    street_address: null,
    full_address:
      "9 Star Lake street, Maitama, Abuja 900271, Federal Capital Territory, Nigeria",
    postal_code: "900271",
    longitude: 7.4956326,
    latitude: 9.088952999999998,
    full_address_url: "https://maps.google.com/?cid=3658452452198643264",
    avatar: "http://api-dev.beezlinq.com/images/user-avatar-placeholder.jpg",
    phone_code: "+234",
    country_code: "234",
    is_first_time: 1,
    email_verified_at: "2023-08-07T14:24:28.000000Z",
    password_updated_at: "2023-12-14 09:28:08",
    is_staff: 0,
    active_subscription_plan_name: "Free",
    active_subscription_start_date: "2024-05-13 15:37:19",
    active_subscription_end_date: "2025-05-13 15:37:19",
    active_subscription_duration: "annual",
    subscriptions: {
      id: 2432,
      amount: "69.86",
      duration: "annual",
      start_date: "2024-05-13T14:37:19.000000Z",
      end_date: "2025-05-13T14:37:19.000000Z",
      on_free_trial: 0,
      status: "active",
      location_details: null,
      plan: {
        id: 5,
        name: "Free",
        card_quantity: "50000",
        scan_quantity: "20",
        base_amount: "6.99",
        monthly_amount: "6.99",
        yearly_amount: "64.99",
        monthly_discount: null,
        yearly_discount: null,
        discount_amount: null,
        discount_percent: null,
        yearly_discount_percent: "22.50",
        monthly_discount_percent: null,
        currency: "USD",
        plan_features: {},
        plan_features_details: [],
        plan_features_details_monthly: [],
        plan_features_details_annually: [],
        location_details: null,
      },
      in_app_plan: null,
    },
    interests: [],
    scan_subscriptions: null,
    system_language: {
      id: 1,
      name: "English",
      abbr: "en",
      status: 1,
      flag: "http://api-dev.beezlinq.com/images/flags/gb.png",
    },
    user_settings: {
      id: 1938,
      user_id: 0,
      two_factor_auth: 0,
      push_notifications: 0,
      biometrics_authentication: 0,
    },
    payment_cards: [],
  },
  properties: [
    {
      id: 1,
      name: "BeniRose 1",
      avatar: "/images/temp/1.jpg",
      price: 1220999,
      rentPrice: 2000,
      sale: 2,
      location: "Maitama Abuja, Abuja - Block A",
      status: "rented",
      category: "Rent",
      features: ["Swimming Pool", "Concierge", "Fitness Center", "Arcade"],
      rating: 4.6,
    },
    {
      id: 2,
      name: "BeniRose 2",
      avatar: "/images/temp/2.jpg",
      rentPrice: 3500,
      price: 2120999,
      sale: 2,
      location: "Maitama Abuja, Abuja - Block C",
      status: "rented",
      category: "Rent",
      features: ["Modern Kitchen", "Concierge", "Gym Access", "Lounge"],
      rating: 4.8,
    },
    {
      id: 3,
      name: "BeniRose 3",
      avatar: "/images/temp/3.jpg",
      rentPrice: 2500,
      price: 2120999,
      sale: 2,
      location: "Maitama Abuja, Abuja  - Block E",
      status: "available",
      category: "Rent",
      features: [
        "Swimming Pool",
        "Concierge",
        "Fitness Center",
        "Office Suite",
      ],
      rating: 4.6,
    },
    {
      id: 4,
      name: "Luxemboug",
      avatar: "/images/temp/4.jpg",
      rentPrice: 2500,
      price: 31222199,
      sale: 5,
      location: "FHA Lugbe, Abuja - Block A1",
      status: "maintanence",
      category: "Sale",
      features: ["River View", "Parking", "Fitness Center", "Concierge"],
      rating: 5,
    },
  ],
};
